import { Metadata } from "next"
import { SidebarNav } from "@/components/ui/sidebar-nav"
import { PROFILE_SETTINGS_INTEGRATION_URL, PROFILE_SETTINGS_PRIVACY_URL, PROFILE_SETTINGS_URL } from "@/const/links"

const sidebarNavItems = [
  {
    title: "Profile",
    href: PROFILE_SETTINGS_URL,
  },
  {
    title: "Integration",
    href: PROFILE_SETTINGS_INTEGRATION_URL,
  },
  {
    title: "Privacy",
    href: PROFILE_SETTINGS_PRIVACY_URL,
  },
]

export const metadata: Metadata = {
  title: "Juku | Profile",
  description: 'Generated by create next app',
}

export default function ProfileSettingsLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="space-y-6 p-10 pb-16">
      <div className="flex flex-col space-y-8 lg:flex-row lg:space-x-12 lg:space-y-0">
        <aside className="-mx-4 lg:w-1/5">
          <SidebarNav items={sidebarNavItems} />
        </aside>
        <div className="flex-1 lg:max-w-2xl">{children}</div>
      </div>
    </div>
  )
}