export const LANDING_PAGE_URL = "https://www.juku.network/";
export const APP_HOMEPAGE_URL = "/";
export const BOUNTY_CREATION_URL = "/bounty/create";
export const CONSULTATION_CREATION_URL = "/consultation/create";
export const LINKEDIN_URL = "https://www.linkedin.com/company/jukunetwork/";
export const TWITTER_URL = "https://x.com/juku_network";
export const TERMS_OF_SERVICE_URL = "https://juku.gitbook.io/juku/other-information/legal/terms-of-use/"; //TODO: TBD
export const HOW_IT_WORKS_URL = "https://juku.gitbook.io/juku";
export const INTRODUCTION_URL = "https://www.juku.network/";
export const CONTACT_US_URL = "mailto:contact@juku.network";
export const PROFILE_URL = "/profile";
export const PROFILE_SETTINGS_URL = "/profile/settings";
export const PROFILE_SETTINGS_INTEGRATION_URL = "/profile/settings/integration";
export const PROFILE_SETTINGS_PRIVACY_URL = "/profile/settings/privacy"; 
export const PROFILE_SETTINGS_NOTIFICATION_URL = "/profile/settings/notification"; 
export const PLATFROM_QUEST_URL = "/profile"; //TODO: TBD
export const FULL_LOGO = "/juku-full.svg";
export const SHORT_LOGO = "/juku-short.svg";
export const COINBASE_VERIFICATION_URL = "https://www.coinbase.com/onchain-verify/";