export const LANDING_PAGE_URL = "https://www.juku.network/";
export const APP_HOMEPAGE_URL = "/";
export const BOUNTY_CREATION_URL = "/bounty/create";
export const CONSULTATION_CREATION_URL = "/consultation/create";
export const LINKEDIN_URL = "https://www.linkedin.com/company/jukunetwork/";
export const TWITTER_URL = "https://twitter.com/jukunetwork";
export const FAQ_URL = "https://www.gitbook.com/"; //TODO: TBD
export const TERMS_OF_SERVICE_URL = "https://juku.gitbook.io/juku/other-information/legal/terms-of-use/"; //TODO: TBD
export const HOW_IT_WORKS_URL = "https://www.gitbook.com/"; //TODO: TBD
export const INTRODUCTION_URL = "https://www.gitbook.com/"; //TODO: TBD
export const CONTACT_US_URL = "https://www.gitbook.com/"; //TODO: TBD
export const PROFILE_URL = "/profile";
export const PROFILE_SETTINGS_URL = "/profile/settings";
export const PROFILE_SETTINGS_INTEGRATION_URL = "/profile/settings/integration";
export const PROFILE_SETTINGS_PRIVACY_URL = "/profile/settings/privacy"; 
export const PROFILE_SETTINGS_NOTIFICATION_URL = "/profile/settings/notification"; 
export const PLATFROM_QUEST_URL = "/profile"; //TODO: TBD
export const JUKU_LOGO = "/juku.svg";