// Bounty topics
import { Option } from '@/components/ui/multiple-selector';

// TODO: show some default hardcoded tags 
// TODO: get from ceramic 
export const TOPIC_OPTIONS: Option[] = [
  { label: 'Startup Idea', value: 'Startup Idea' },
  { label: 'Entrepreneur Advice', value: 'Entrepreneur Advice' },
  { label: 'Financing', value: 'Financing' },
  { label: 'Growth Strategy', value: 'Growth Strategy' },
  { label: 'User Acquisition', value: 'User Acquisition' },
  { label: 'Partnership', value: 'Partnership' },
  { label: 'Proudct Management', value: 'Proudct Management' },
  { label: 'Product Marketing', value: 'Product Marketing' },
  { label: 'Product Design', value: 'Product Design' },
  { label: 'Graphic Design', value: 'Graphic Design' },
  { label: 'Architecture', value: 'Architecture' },
  { label: 'Photography', value: 'Photography' },
  { label: 'DeFi', value: 'DeFi' },
  { label: 'NFT', value: 'NFT' },
  { label: 'DeSoc', value: 'DeSoc' },
  { label: 'DePIN', value: 'DePIN' },
  { label: 'RWA', value: 'RWA' },
  { label: 'Memecoins', value: 'Memecoins' },
  { label: 'Wallets & Payment', value: 'Wallets & Payment' },
  { label: 'L2/L3', value: 'L2/L3' },
  { label: 'EVM', value: 'EVM' },
  { label: 'BTC', value: 'BTC' },
  { label: 'Cosmos/IBC', value: 'Cosmos/IBC' },
  { label: 'Go-to-Market', value: 'Go-to-Market' },
  { label: 'Public Relations', value: 'Public Relations' },
  { label: 'SEO', value: 'SEO' },
  { label: 'Social Media Marketing', value: 'Social Media Marketing' },
  { label: 'Advertising', value: 'Advertising' },
  { label: 'Affiliate Marketing', value: 'Affiliate Marketing' },
  { label: 'Marketing Strategy', value: 'Marketing Strategy' },
  { label: 'Branding', value: 'Branding' },
  { label: 'Discord', value: 'Discord' },
  { label: 'Twitter/X', value: 'Twitter/X' },
  { label: 'Telegram', value: 'Telegram' },
  { label: 'Medium', value: 'Medium' },
  { label: 'Facebook', value: 'Facebook' },
  { label: 'Instagram', value: 'Instagram' },
  { label: 'Machine Learning', value: 'Machine Learning' },
  { label: 'Deep Learning', value: 'Deep Learning' },
  { label: 'Robotics', value: 'Robotics' },
  { label: 'AI Tools', value: 'AI Tools' },
  { label: 'Recruiting', value: 'Recruiting' },
  { label: 'Job Interviews', value: 'Job Interviews' },
  { label: 'Employees', value: 'Employees' },
  { label: 'Employers', value: 'Employers' },
  { label: 'Investing', value: 'Investing' },
  { label: 'Personal Finance', value: 'Personal Finance' },
  { label: 'Investment Advice', value: 'Investment Advice' },
  { label: 'Investment Strategies', value: 'Investment Strategies' },
  { label: 'Economics', value: 'Economics' },
  { label: 'Banking', value: 'Banking' },
  { label: 'Market Insights', value: 'Market Insights' },
  { label: 'Compliance', value: 'Compliance' },
  { label: 'Employment Law', value: 'Employment Law' },
  { label: 'Taxation', value: 'Taxation' },
  { label: 'Medicine & Healthcare', value: 'Medicine & Healthcare' },
  { label: 'Nutrition', value: 'Nutrition' },
  { label: 'Healthy Eating', value: 'Healthy Eating' },
  { label: 'Exercise', value: 'Exercise' },
  { label: 'Video Games', value: 'Video Games' },
  { label: 'PC Gaming', value: 'PC Gaming' },
  { label: 'Game Development', value: 'Game Development' },
  { label: 'Mobile Games', value: 'Mobile Games' },
  { label: 'PUBG', value: 'PUBG' },
  { label: 'Game Design', value: 'Game Design' },
  { label: 'Online Multiplayer Gaming', value: 'Online Multiplayer Gaming' },
  { label: 'Musicians', value: 'Musicians' },
  { label: 'Musical Instruments', value: 'Musical Instruments' },
  { label: 'Songs', value: 'Songs' },
  { label: 'TV Show', value: 'TV Show' },
  { label: 'Youtube Videos', value: 'Youtube Videos' },
  { label: 'Movies', value: 'Movies' },
  { label: 'Schools, College & Universities', value: 'Schools, College & Universities' },
  { label: 'Exams & Tests', value: 'Exams & Tests' },
  { label: 'Academic & Educational Advice', value: 'Academic & Educational Advice' },
  { label: 'Higher Education', value: 'Higher Education' },
  { label: 'Students', value: 'Students' },
  { label: 'Teachers', value: 'Teachers' },
];
