import { Metadata } from "next"

export const metadata: Metadata = {
  title: "Juku | Bounty",
  description: 'Generated by create next app', // TODO: update this
}

export default function BountyLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="space-y-6 md:px-10 py-10 pb-16">
      <div className="flex flex-col space-y-8 lg:flex-row lg:space-x-12 lg:space-y-0">
        <div className="flex-1">{children}</div>
      </div>
    </div>
  )
}