INSERT INTO Tag (name, slug, created_at, edited_at)
VALUES 
('Startup Idea', 'startup_idea', NOW(), NOW()),
('Entrepreneur Advice', 'entrepreneur_advice', NOW(), NOW()),
('Financing', 'financing', NOW(), NOW()),
('Growth Strategy', 'growth_strategy', NOW(), NOW()),
('User Acquisition', 'user_acquisition', NOW(), NOW()),
('Partnership', 'partnership', NOW(), NOW()),
('Proudct Management', 'proudct_management', NOW(), NOW()),
('Product Marketing', 'product_marketing', NOW(), NOW()),
('Product Design', 'product_design', NOW(), NOW()),
('Graphic Design', 'graphic_design', NOW(), NOW()),
('Architecture', 'architecture', NOW(), NOW()),
('Photography', 'photography', NOW(), NOW()),
('DeFi', 'defi', NOW(), NOW()),
('NFT', 'nft', NOW(), NOW()),
('DeSoc', 'desoc', NOW(), NOW()),
('DePIN', 'depin', NOW(), NOW()),
('RWA', 'rwa', NOW(), NOW()),
('Memecoins', 'memecoins', NOW(), NOW()),
('Wallets & Payment', 'wallets_payment', NOW(), NOW()),
('L2/L3', 'l2_l3', NOW(), NOW()),
('EVM', 'evm', NOW(), NOW()),
('BTC', 'btc', NOW(), NOW()),
('Cosmos/IBC', 'cosmos_ibc', NOW(), NOW()),
('Go-to-Market', 'go_to_market', NOW(), NOW()),
('Public Relations', 'public_relations', NOW(), NOW()),
('SEO', 'seo', NOW(), NOW()),
('Social Media Marketing', 'social_media_marketing', NOW(), NOW()),
('Advertising', 'advertising', NOW(), NOW()),
('Affiliate Marketing', 'affiliate_marketing', NOW(), NOW()),
('Marketing Strategy', 'marketing_strategy', NOW(), NOW()),
('Branding', 'branding', NOW(), NOW()),
('Discord', 'discord', NOW(), NOW()),
('Twitter/X', 'twitter_x', NOW(), NOW()),
('Telegram', 'telegram', NOW(), NOW()),
('Medium', 'medium', NOW(), NOW()),
('Facebook', 'facebook', NOW(), NOW()),
('Instagram', 'instagram', NOW(), NOW()),
('Machine Learning', 'machine_learning', NOW(), NOW()),
('Deep Learning', 'deep_learning', NOW(), NOW()),
('Robotics', 'robotics', NOW(), NOW()),
('AI Tools', 'ai_tools', NOW(), NOW()),
('Recruiting', 'recruiting', NOW(), NOW()),
('Job Interviews', 'job_interviews', NOW(), NOW()),
('Employees', 'employees', NOW(), NOW()),
('Employers', 'employers', NOW(), NOW()),
('Investing', 'investing', NOW(), NOW()),
('Personal Finance', 'personal_finance', NOW(), NOW()),
('Investment Advice', 'investment_advice', NOW(), NOW()),
('Investment Strategies', 'investment_strategies', NOW(), NOW()),
('Economics', 'economics', NOW(), NOW()),
('Banking', 'banking', NOW(), NOW()),
('Market Insights', 'market_insights', NOW(), NOW()),
('Compliance', 'compliance', NOW(), NOW()),
('Employment Law', 'employment_law', NOW(), NOW()),
('Taxation', 'taxation', NOW(), NOW()),
('Medicine & Healthcare', 'medicine_healthcare', NOW(), NOW()),
('Nutrition', 'nutrition', NOW(), NOW()),
('Healthy Eating', 'healthy_eating', NOW(), NOW()),
('Exercise', 'exercise', NOW(), NOW()),
('Video Games', 'video_games', NOW(), NOW()),
('PC Gaming', 'pc_gaming', NOW(), NOW()),
('Game Development', 'game_development', NOW(), NOW()),
('Mobile Games', 'mobile_games', NOW(), NOW()),
('PUBG', 'pubg', NOW(), NOW()),
('Game Design', 'game_design', NOW(), NOW()),
('Online Multiplayer Gaming', 'online_multiplayer_gaming', NOW(), NOW()),
('Musicians', 'musicians', NOW(), NOW()),
('Musical Instruments', 'musical_instruments', NOW(), NOW()),
('Songs', 'songs', NOW(), NOW()),
('TV Show', 'tv_show', NOW(), NOW()),
('Youtube Videos', 'youtube_videos', NOW(), NOW()),
('Movies', 'movies', NOW(), NOW()),
('Schools, College & Universities', 'schools_college_universities', NOW(), NOW()),
('Exams & Tests', 'exams_tests', NOW(), NOW()),
('Academic & Educational Advice', 'academic_educational_advice', NOW(), NOW()),
('Higher Education', 'higher_education', NOW(), NOW()),
('Students', 'students', NOW(), NOW()),
('Teachers', 'teachers', NOW(), NOW());
